development:
  adapter: postgresql
  encoding: unicode
  database: demo_test_development2
  pool: 5
  username: peyton
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: demo_test_test2
  pool: 5
  username: peyton
  password:
  timeout: 5000
